force-app/main/default/objects/Opporunity_Script_Junction__c/Opporunity_Script_Junction__c.object-meta.xml
<CustomObject>
    <label>Opporunity Script Junction</label>
    <nameField>
        <label>Opporunity Script Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opporunity Script Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opporunity_Script_Junction__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opporunity Script Junctions O</relationshipLabel>
    <relationshipName>Opporunity_Script_Junctions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opporunity_Script_Junction__c/fields/Opporunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opporunity_Stage__c</fullName>
    <description>Captures the stage of the opportunity when this record was created.</description>
    <label>Opporunity Stage</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opporunity_Script_Junction__c/fields/Related_User__c.field-meta.xml
<CustomField>
    <fullName>Related_User__c</fullName>
    <formula>Sales_Rep_Script__r.scriptUser__r.LastName+
IF(ISBLANK(Sales_Rep_Script__r.scriptUser__r.FirstName),
  &quot;&quot;,
  &quot;, &quot;+Sales_Rep_Script__r.scriptUser__r.FirstName
)</formula>
    <label>Related User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opporunity_Script_Junction__c/fields/Related_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_User_Id__c</fullName>
    <formula>Sales_Rep_Script__r.scriptUser__c</formula>
    <label>Related User Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opporunity_Script_Junction__c/fields/Sales_Rep_Script__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Script__c</fullName>
    <label>Sales Rep Script</label>
    <referenceTo>Sales_Rep_Script__c</referenceTo>
    <relationshipLabel>Opporunity Script Junctions S</relationshipLabel>
    <relationshipName>Opporunity_Script_Junctions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Script__c/Sales_Rep_Script__c.object-meta.xml
<CustomObject>
    <label>Sales Rep Script</label>
    <nameField>
        <label>Sales Rep Scripts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Rep_Script__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To store an opportunity specified for a script.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Rep Scripts</relationshipLabel>
    <relationshipName>Sales_Rep_Scripts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Script__c/fields/scriptUser__c.field-meta.xml
<CustomField>
    <fullName>scriptUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>scriptUser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Rep_Scripts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Script_Metric__c/Script_Metric__c.object-meta.xml
<CustomObject>
    <description>Keeps track of how far an opportunity progresses with a given set of scripts. Used to collect information on usefulness of scripts.</description>
    <label>Script Metric</label>
    <nameField>
        <label>Script Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Script Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Script_Metric__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Script Metrics</relationshipLabel>
    <relationshipName>Script_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Script_Metric__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <description>Keeps track of the last stage the opportunity made it to.</description>
    <label>Opportunity Stage</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Script_Metric__c/fields/Related_User__c.field-meta.xml
<CustomField>
    <fullName>Related_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If there is a script for a specific user, then that gets added to the metric record. There is a version of this record without any users tied to it and then copies for different users. Since a user may have specific scripts assigned to him or her leading to a different set of scripts of an opportunity.</description>
    <label>Related User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Script_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Script_Metric__c/fields/Scripts_Used__c.field-meta.xml
<CustomField>
    <fullName>Scripts_Used__c</fullName>
    <description>Stores a comma-sepparated list of stage names to script ids i.e. prospectin:scriptId1,Qualification:ScriptId2</description>
    <label>Scripts Used</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MetricObjectHandler.cls
public with sharing class MetricObjectHandler {
    /**
     * Handle creation or update of a Script_Metric__c record that will keep track of the scripts used for an opportunity
     */
    @AuraEnabled
    public static void handleMetricObject(Opportunity opp) {
        System.debug('Running after update.');
        ScriptHandler sh = new ScriptHandler(opp);
        
        List<Sales_Rep_Script__c> scripts = sh.getScriptObjects(opp.Type, opp.StageName);
        if(scripts.isEmpty()) {
            return;
        }
        Sales_Rep_Script__c script = ScriptDisplayController.getMostSpecific(scripts);
        System.debug(script.Name);

        upsertMetric(opp, script);
        upsertJunctionObject(opp, script);
    } 

    private static Script_Metric__c setCommonFieldAssignments(Script_Metric__c metric, Opportunity opp, Sales_Rep_Script__c script) {
        if(metric == null) {
            metric = new Script_Metric__c();
        }
        if(metric.Opportunity__c == null) {
            metric.Opportunity__c = opp.Id;
        }
        metric.Opportunity_Stage__c = opp.StageName;
        metric.Scripts_Used__c = AscendUtils.addToDelimitedSet(metric.Scripts_Used__c, opp.StageName + ':' + script.Id, ';');
        if(opp.StageName == 'Closed Won') {
            metric.jgaude__Opportunity_Won__c = true;
        }
        else {
            metric.jgaude__Opportunity_Won__c = false;
        }
        return metric;
    } 

    private static void upsertMetric(Opportunity opp, Sales_Rep_Script__c script) {
        Script_Metric__c metric = ScriptDisplayController.getMetricRecord(opp.Id);

        if(metric == null) { 

            metric = setCommonFieldAssignments(metric, opp, script);
            if(script.scriptUser__c == UserInfo.getUserId()) {
                metric.Related_User__c = script.scriptUser__c;
            }

            if(Script_Metric__c.sObjectType.getDescribe().isCreateable()) {
                insert metric;
            }
        } else if(metric != null && metric.Related_User__c == null && script.scriptUser__c == UserInfo.getUserId()) {

            Script_Metric__c newMetric = setCommonFieldAssignments(null, opp, script);
            newMetric.Related_User__c = script.scriptUser__c;
            if(Script_Metric__c.sObjectType.getDescribe().isCreateable()) {
                insert newMetric;
            }
        } else {

            metric = setCommonFieldAssignments(metric, opp, script);
            if(Script_Metric__c.sObjectType.getDescribe().isUpdateable()) {
                update metric;
            }
        }
    }

    private static void upsertJunctionObject(Opportunity opp, Sales_Rep_Script__c script) {
        Opporunity_Script_Junction__c junct = ScriptDisplayController.getJunctionRecord(opp.Id, script.Id);
        
        if(junct == null) {
            junct = new Opporunity_Script_Junction__c();
            junct.Opporunity_Stage__c = opp.StageName;
            junct.Opportunity__c = opp.Id;
            junct.Sales_Rep_Script__c = script.Id;
            if(Opporunity_Script_Junction__c.sObjectType.getDescribe().isCreateable()) {
                insert junct;
            }
        }
        else if(junct != null && junct.Related_User_Id__c == null && script.scriptUser__c == UserInfo.getUserId()) {
            junct = new Opporunity_Script_Junction__c();
            junct.Opporunity_Stage__c = opp.StageName;
            junct.Opportunity__c = opp.Id;
            junct.Sales_Rep_Script__c = script.Id;
            if(Opporunity_Script_Junction__c.sObjectType.getDescribe().isCreateable()) {
                insert junct;
            }
        }
        else {
            junct.Opporunity_Stage__c = opp.StageName;
            if(Opporunity_Script_Junction__c.sObjectType.getDescribe().isUpdateable()) {
                update junct;
            }
        }
    }
    
}