force-app/main/default/objects/Sales_Rep_Script__c/Sales_Rep_Script__c.object-meta.xml
<CustomObject>
    <label>Sales Rep Script</label>
    <nameField>
        <label>Sales Rep Scripts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Rep_Script__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To store an opportunity specified for a script.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Rep Scripts</relationshipLabel>
    <relationshipName>Sales_Rep_Scripts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Script__c/fields/OpportunityType__c.field-meta.xml
<CustomField>
    <fullName>OpportunityType__c</fullName>
    <label>OpportunityType</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Script__c/fields/scriptUser__c.field-meta.xml
<CustomField>
    <fullName>scriptUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>scriptUser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Rep_Scripts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Script_Metric__c/Script_Metric__c.object-meta.xml
<CustomObject>
    <description>Keeps track of how far an opportunity progresses with a given set of scripts. Used to collect information on usefulness of scripts.</description>
    <label>Script Metric</label>
    <nameField>
        <label>Script Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Script Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Script_Metric__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Script Metrics</relationshipLabel>
    <relationshipName>Script_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Script_Metric__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <description>Keeps track of the last stage the opportunity made it to.</description>
    <label>Opportunity Stage</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Script_Metric__c/fields/Opportunity_Won__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Won__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mark if an Opportunity is won</description>
    <label>Opportunity Won</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Script_Metric__c/fields/Related_User__c.field-meta.xml
<CustomField>
    <fullName>Related_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If there is a script for a specific user, then that gets added to the metric record. There is a version of this record without any users tied to it and then copies for different users. Since a user may have specific scripts assigned to him or her leading to a different set of scripts of an opportunity.</description>
    <label>Related User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Script_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Script_Metric__c/fields/Scripts_Used__c.field-meta.xml
<CustomField>
    <fullName>Scripts_Used__c</fullName>
    <description>Stores a comma-sepparated list of stage names to script ids i.e. prospectin:scriptId1,Qualification:ScriptId2</description>
    <label>Scripts Used</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ScriptDisplayCtrl_Test.cls
@isTest
public class ScriptDisplayCtrl_Test {
    
    @TestSetup
    static void makeData(){
        Opportunity opp = AscendTestDataFactory.createOpportunity(null);

        AscendTestDataFactory.autoCommit = false;
        Sales_Rep_Script__c script1 = AscendTestDataFactory.createScript(new Map<SObjectField,Object>{
            Sales_Rep_Script__c.OpportunityType__c => 'New Customer'
        });
        Sales_Rep_Script__c script2 = AscendTestDataFactory.createScript(new Map<SObjectField,Object>{
            Sales_Rep_Script__c.Opportunity__c => opp.Id
        });
        AscendTestDataFactory.autoCommit = true;
    }

    @isTest
    static void testGetScript() {
        Opportunity opp = [SELECT Id FROM Opportunity];
        Sales_Rep_Script__c script1 = [SELECT Id FROM Sales_Rep_Script__c WHERE Opportunity__c = :opp.Id];

        Test.startTest();
        Map<String,Sales_Rep_Script__c> scriptMap = ScriptDisplayController.getScript(opp.Id);
        Test.stopTest();

        System.assertEquals(script1.Id, scriptMap.get('Prospecting').Id);
    }

    @isTest
    static void testHandleMetric() {
        Opportunity opp = [SELECT StageName, Type FROM Opportunity];
        Sales_Rep_Script__c script1 = [SELECT Id FROM Sales_Rep_Script__c WHERE Opportunity__c = :opp.Id];
        Test.startTest();
        ScriptDisplayController.handleMetricObject(opp);
        Test.stopTest();

        Script_Metric__c metric = [SELECT Opportunity_Stage__c, Opportunity_Won__c, Scripts_Used__c FROM Script_Metric__c WHERE Opportunity__c = :opp.Id];

        System.assertEquals('Prospecting', metric.Opportunity_Stage__c);
        System.assertEquals(false, metric.Opportunity_Won__c);
        System.assertEquals(opp.StageName + ':' + script1.Id, metric.Scripts_Used__c);
    }

    @isTest
    static void testHandleMetricWithUserId() {
        Opportunity opp = [SELECT StageName, Type FROM Opportunity];
        Sales_Rep_Script__c script1 = [SELECT Id FROM Sales_Rep_Script__c WHERE Opportunity__c = :opp.Id];
        
        Test.startTest();
        ScriptDisplayController.handleMetricObject(opp);
        script1.scriptUser__c = UserInfo.getUserId();
        update script1;
        ScriptDisplayController.handleMetricObject(opp);
        script1.scriptUser__c = null;
        update script1;
        ScriptDisplayController.handleMetricObject(opp);
        Test.stopTest();

        Script_Metric__c metric = [SELECT Opportunity_Stage__c, Opportunity_Won__c, Scripts_Used__c, Related_User__c FROM Script_Metric__c 
        WHERE Opportunity__c = :opp.Id AND Related_User__c = :UserInfo.getUserId()];

        System.assertEquals('Prospecting', metric.Opportunity_Stage__c);
        System.assertEquals(false, metric.Opportunity_Won__c);
        System.assertEquals(opp.StageName + ':' + script1.Id, metric.Scripts_Used__c);
        System.assertEquals(UserInfo.getUserId(), metric.Related_User__c);
        System.assertEquals(2, [SELECT Opportunity_Stage__c, Opportunity_Won__c, Scripts_Used__c, Related_User__c FROM Script_Metric__c].size());
    }

    @isTest
    static void testShouldButtonBeDisabled() {
        Opportunity opp = [SELECT StageName, Type FROM Opportunity];

        Test.startTest();
        ScriptDisplayController.handleMetricObject(opp);
        Boolean btnDisabled = ScriptDisplayController.shouldButtonBeDisabled(opp.Id);
        Test.stopTest();

        System.assert(btnDisabled);
    }

    @isTest
    static void testShouldButtonBeDisabledNoScript() {
        Opportunity opp = [SELECT StageName, Type FROM Opportunity];

        Test.startTest();
        ScriptDisplayController.handleMetricObject(opp);
        opp.StageName = 'Qualification';
        update opp;
        Boolean btnDisabled = ScriptDisplayController.shouldButtonBeDisabled(opp.Id);
        Test.stopTest();

        System.assert(btnDisabled);
    }

    @isTest
    static void testShouldButtonBeDisabledFalse() {
        Opportunity opp = [SELECT StageName FROM Opportunity];

        Test.startTest();
        Boolean btnDisabled = ScriptDisplayController.shouldButtonBeDisabled(opp.Id);
        Test.stopTest();

        System.assertEquals(false, btnDisabled);
    }
}