force-app/main/default/objects/Sales_Rep_Script__c/Sales_Rep_Script__c.object-meta.xml
<CustomObject>
    <label>Sales Rep Script</label>
    <nameField>
        <label>Sales Rep Scripts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Rep_Script__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To store an opportunity specified for a script.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Rep Scripts</relationshipLabel>
    <relationshipName>Sales_Rep_Scripts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Script__c/fields/OpportunityType__c.field-meta.xml
<CustomField>
    <fullName>OpportunityType__c</fullName>
    <label>OpportunityType</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SalesRepScriptTrig_Test.cls
@isTest
public class SalesRepScriptTrig_Test {

    /**
     * Test that the trigger prevents a script with identical filters to another from being inserted.
     */
    @isTest
    static void testDuplicateScript() {
        Opportunity opp = AscendTestDataFactory.createOpportunity(null);
        try{
            Sales_Rep_Script__c script1 = AscendTestDataFactory.createScript(new Map<SObjectField,Object>{
                Sales_Rep_Script__c.Opportunity__c => opp.Id,
                Sales_Rep_Script__c.OpportunityType__c => 'New Customer'
            });
            Sales_Rep_Script__c script2 = AscendTestDataFactory.createScript(new Map<SObjectField,Object>{
                Sales_Rep_Script__c.Opportunity__c => opp.Id,
                Sales_Rep_Script__c.OpportunityType__c => 'New Customer'
            });
        } catch(Exception e) {
            System.assert(e.getMessage().contains(errStrPartial));
        }
    }

    static String errStrPartial = 'is already using the combination of filters that you are trying to select. You must select a unique combination of filters, or mark this script or';
}