force-app/main/default/objects/Sales_Rep_Script__c/Sales_Rep_Script__c.object-meta.xml
<CustomObject>
    <label>Sales Rep Script</label>
    <nameField>
        <label>Sales Rep Scripts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Rep_Script__c/fields/scriptUser__c.field-meta.xml
<CustomField>
    <fullName>scriptUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>scriptUser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Rep_Scripts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ScriptEditorControllerHelper.cls
public without sharing class ScriptEditorControllerHelper {

    /**
     * In general a script user is not allowed to create a script. The exception is when 
     * the user is "moddifying" the script to personalize it. In this case we are
     * duplicating the script and associating it with this user if a personalized one
     * does not already exist to be updated. This duplication requires a record to be
     * inserted.
     * 
     * The record can only be inserted buy a script user through the script editor page
     * and the scriptUser__c must the user's Id. 
     */
    public static void saveScript(Sales_Rep_Script__c script) {
        if(Sales_Rep_Script__c.sObjectType.getDescribe().isAccessible() &&
        (Sales_Rep_Script__c.sObjectType.getDescribe().isCreateable() || script.scriptUser__c == UserInfo.getUserId()) &&
        Sales_Rep_Script__c.sObjectType.getDescribe().isUpdateable()) {
            upsert script;
        }
    }
}