force-app/main/default/objects/Sales_Rep_Script__c/Sales_Rep_Script__c.object-meta.xml
<CustomObject>
    <label>Sales Rep Script</label>
    <nameField>
        <label>Sales Rep Scripts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Rep_Script__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <label>Script</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Script__c/fields/scriptUser__c.field-meta.xml
<CustomField>
    <fullName>scriptUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>scriptUser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Rep_Scripts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ScriptDisplayController_Test.cls
@isTest
public class ScriptDisplayController_Test {

    @TestSetup
    static void makeData(){
        User u = AscendTestDataFactory.createUser(new Map<SObjectField,Object>{User.FirstName => 'John', User.LastName => 'Doe'});

        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Script_User'];
        System.runas(new User(ID = UserInfo.getUserID())) {
            PermissionSetAssignment psa = new PermissionSetAssignment(PermissionSetId = ps.Id, AssigneeId = u.Id);
            insert psa;
        }
        AscendTestDataFactory.autoCommit = false;
        AscendTestDataFactory.createOpportunity(null);
        AscendTestDataFactory.createScript(new Map<SObjectField,Object>{
            Sales_Rep_Script__c.Name => 'Script 1',
            Sales_Rep_Script__c.Script__c => 'The script for the test opportunity {Opportunity.Name}'
        });
        AscendTestDataFactory.createScript(new Map<SObjectField,Object>{
            Sales_Rep_Script__c.Name => 'Script 2',
            Sales_Rep_Script__c.scriptUser__c => u.Id,
            Sales_Rep_Script__c.Script__c => 'The script for the test opportunity {Opportunity.Name}'
        });
        AscendTestDataFactory.autoCommit = true;
    }
    
    @isTest
    static void getScript() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

        Test.startTest();
        Map<String,Sales_Rep_Script__c> scriptMap = ScriptDisplayController.getScript(opp.Id);
        Test.stopTest();

        System.assertEquals('Script 1', scriptMap.get('Prospecting').Name, 'Script 1 should have been selected but was not.');
    }

    @isTest
    static void getScriptWithUser() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        User u = [SELECT Id FROM User WHERE Email LIKE 'testUser%'];

        Map<String,Sales_Rep_Script__c> scriptMap;
        System.runAs(u) {
            Test.startTest();
            scriptMap = ScriptDisplayController.getScript(opp.Id);
            Test.stopTest();
        }

        System.assertEquals('Script 2', scriptMap.get('Prospecting').Name, 'Script 2 should have been selected but was not.');
    }
}