force-app/main/default/objects/Opportunity_Listen__e/Opportunity_Listen__e.object-meta.xml
<CustomObject>
    <description>Continuously Listen to Opportunities</description>
    <label>Opportunity Listen</label>
    <pluralLabel>Opportunity Listens</pluralLabel>
</CustomObject>

force-app/main/default/objects/Opportunity_Listen__e/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Opportunity stage name.</description>
    <label>Stage</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opporunity_Script_Junction__c/Opporunity_Script_Junction__c.object-meta.xml
<CustomObject>
    <label>Opporunity Script Junction</label>
    <nameField>
        <label>Opporunity Script Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opporunity Script Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opporunity_Script_Junction__c/fields/Date_Won__c.field-meta.xml
<CustomField>
    <fullName>Date_Won__c</fullName>
    <description>Timestamp for when the opportunity was won.</description>
    <label>Date Won</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opporunity_Script_Junction__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opporunity Script Junctions O</relationshipLabel>
    <relationshipName>Opporunity_Script_Junctions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opporunity_Script_Junction__c/fields/Opporunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opporunity_Stage__c</fullName>
    <description>Captures the stage of the opportunity when this record was created.</description>
    <label>Opporunity Stage</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opporunity_Script_Junction__c/fields/Opporunity_Won__c.field-meta.xml
<CustomField>
    <fullName>Opporunity_Won__c</fullName>
    <formula>Opportunity__r.IsWon</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opporunity Won</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opporunity_Script_Junction__c/fields/Sales_Rep_Script__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Script__c</fullName>
    <label>Sales Rep Script</label>
    <referenceTo>Sales_Rep_Script__c</referenceTo>
    <relationshipLabel>Opporunity Script Junctions S</relationshipLabel>
    <relationshipName>Opporunity_Script_Junctions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Script__c/Sales_Rep_Script__c.object-meta.xml
<CustomObject>
    <label>Sales Rep Script</label>
    <nameField>
        <label>Sales Rep Scripts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Rep_Script__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To store an opportunity specified for a script.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Rep Scripts</relationshipLabel>
    <relationshipName>Sales_Rep_Scripts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Script__c/fields/OpportunityStage__c.field-meta.xml
<CustomField>
    <fullName>OpportunityStage__c</fullName>
    <label>OpportunityStage</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Script_Metric__c/Script_Metric__c.object-meta.xml
<CustomObject>
    <description>Keeps track of how far an opportunity progresses with a given set of scripts. Used to collect information on usefulness of scripts.</description>
    <label>Script Metric</label>
    <nameField>
        <label>Script Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Script Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Script_Metric__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Script Metrics</relationshipLabel>
    <relationshipName>Script_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Script_Metric__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <description>Keeps track of the last stage the opportunity made it to.</description>
    <label>Opportunity Stage</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Script_Metric__c/fields/Opportunity_Won__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Won__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mark if an Opportunity is won</description>
    <label>Opportunity Won</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Script_Metric__c/fields/Scripts_Used__c.field-meta.xml
<CustomField>
    <fullName>Scripts_Used__c</fullName>
    <description>Stores a comma-sepparated list of stage names to script ids i.e. prospectin:scriptId1,Qualification:ScriptId2</description>
    <label>Scripts Used</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandler_Test.cls
@isTest
public class OpportunityTriggerHandler_Test {
    
    @TestSetup
    static void makeData(){
        Sales_Rep_Script__c script = AscendTestDataFactory.createScript(null);
        Sales_Rep_Script__c script2 = AscendTestDataFactory.createScript(new Map<SObjectField,Object>{
            Sales_Rep_Script__c.OpportunityStage__c => 'Qualification'
        });
        Opportunity opp = AscendTestDataFactory.createOpportunity(null);
        Script_Metric__c metric = new Script_Metric__c(
            Opportunity__c = opp.Id,
            Scripts_Used__c = opp.StageName + ':' + script.Id,
            Opportunity_Stage__c = 'Prospecting'
        );
        Opporunity_Script_Junction__c junct = new Opporunity_Script_Junction__c(
            Opportunity__c = opp.Id,
            Sales_Rep_Script__c = script.Id,
            Opporunity_Stage__c = 'Prospecting'
        );
        //Opporunity_Script_Junction__c junct2 = new Opporunity_Script_Junction__c(
        //    Opportunity__c = opp.Id,
        //    Sales_Rep_Script__c = script.Id,
        //    Opporunity_Stage__c = 'Closed Won'
        //);
        insert new List<SObject>{metric, junct};
    }

    static User getAdminUser() {
        User u = [SELECT Name FROM User WHERE Profile.Name = 'System Administrator' LIMIT 1];
        AscendTestDataFactory.assignPermissionSets(new Set<User>{u}, new Set<String>{'Script_Admin', 'Script_User'});
        return u;
    }

    @isTest
    static void testFirePlatformEvent() {
        System.runAs(getAdminUser()) {
            Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

            Test.startTest();
            opp.StageName = 'Qualification';
            update opp;
            Test.stopTest();

            List<Opportunity_Listen__e> olList = OpportunityTriggerHandler.events;

            System.assertEquals(1, olList.size(), 'One Opportunity_Listen__e should have been created');
            System.assertEquals('Stage updated.', olList[0].Message__c, 'Event\'s message should be "Stage updated."');
            System.assertEquals('Qualification', olList[0].Stage__c, 'Event\'s stage should be "Qualification"');
            System.assertEquals(String.valueOf(opp.Id),olList[0].OpportunityId__c, 'Event\'s opportunity Id stored does not match the Id of the opportunity updated.');
        }
    }

    @isTest
    static void testUpdateMetricObject() {
        System.runAs(getAdminUser()) {
            Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

            Test.startTest();
            opp.StageName = 'Qualification';
            update opp;

            Script_Metric__c metric = [SELECT Opportunity_Won__c FROM Script_Metric__c LIMIT 1];
            System.assertEquals(false, metric.Opportunity_Won__c, 'The metric should record false for Opportunity_Won__c');

            opp.StageName = 'Closed Won';
            update opp;
            Test.stopTest();

            metric = [SELECT Opportunity_Won__c FROM Script_Metric__c LIMIT 1];
            System.assertEquals(true, metric.Opportunity_Won__c, 'The metric should record true for Opportunity_Won__c');
        }
    }

    @isTest 
    static void testUpdateScriptJunction() {
        System.runAs(getAdminUser()) {
            Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

            Test.startTest();
            opp.StageName = 'Qualification';
            update opp;

            Opporunity_Script_Junction__c junct = [SELECT Date_Won__c, Opporunity_Won__c FROM Opporunity_Script_Junction__c LIMIT 1];
            System.assertEquals(false, junct.Opporunity_Won__c, 'The junction should record false for Opporunity_Won__c');
            System.assertEquals(null, junct.Date_Won__c, 'A date should only be set when the opportunity is won.');

            opp.StageName = 'Closed Won';
            update opp;
            Test.stopTest();

            junct = [SELECT Date_Won__c, Opporunity_Won__c FROM Opporunity_Script_Junction__c][1];
            System.assertEquals(true, junct.Opporunity_Won__c, 'The junction should record true for Opporunity_Won__c');
            System.assertEquals(Date.today(), junct.Date_Won__c, 'A date should only be set when the opportunity is won.');
        }
    }

}