force-app/main/default/objects/Opportunity_Listen__e/Opportunity_Listen__e.object-meta.xml
<CustomObject>
    <description>Continuously Listen to Opportunities</description>
    <label>Opportunity Listen</label>
    <pluralLabel>Opportunity Listens</pluralLabel>
</CustomObject>

force-app/main/default/objects/Opporunity_Script_Junction__c/Opporunity_Script_Junction__c.object-meta.xml
<CustomObject>
    <label>Opporunity Script Junction</label>
    <nameField>
        <label>Opporunity Script Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opporunity Script Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opporunity_Script_Junction__c/fields/Date_Won__c.field-meta.xml
<CustomField>
    <fullName>Date_Won__c</fullName>
    <description>Timestamp for when the opportunity was won.</description>
    <label>Date Won</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opporunity_Script_Junction__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opporunity Script Junctions O</relationshipLabel>
    <relationshipName>Opporunity_Script_Junctions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Script_Metric__c/Script_Metric__c.object-meta.xml
<CustomObject>
    <description>Keeps track of how far an opportunity progresses with a given set of scripts. Used to collect information on usefulness of scripts.</description>
    <label>Script Metric</label>
    <nameField>
        <label>Script Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Script Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Script_Metric__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Script Metrics</relationshipLabel>
    <relationshipName>Script_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Script_Metric__c/fields/Opportunity_Won__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Won__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mark if an Opportunity is won</description>
    <label>Opportunity Won</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandler.cls
/**
 * Note to come back and see if we still need this trigger handler and related trigger, OpportunityTrigger.
 */
public class OpportunityTriggerHandler {
    public static void afterInsert(Map<Id,SObject> newOpps) {

    }

    public static void afterUpdate(Map<Id,SObject> oldOpps, Map<Id,SObject> newOpps) {
        updateMetricObject(oldOpps, newOpps);
        updateScriptJunctionObject(oldOpps, newOpps);
        firePlatformEvents(oldOpps, newOpps);
    }

    private static void firePlatformEvents(Map<Id,SObject> oldOpps, Map<Id,SObject> newOpps) {
        List<SObject> events = new List<SObject>();

        for(Id oppId: oldOpps.keySet()) {
            if(oldOpps.get(oppId).get('StageName') != newOpps.get(oppId).get('StageName')) {
                Opportunity_Listen__e ol = new Opportunity_Listen__e(
                    Message__c = 'Stage updated.',
                    OpportunityId__c = String.valueOf(oppId)
                );
                events.add(ol);
            }
        }
        List<Database.SaveResult> saveResults = Eventbus.publish(events);
        for(Database.SaveResult sr: saveResults) {
            if (sr.isSuccess()) {
                System.debug('Successfully published event. ID: ' + sr.getId());
            } else {
                for(Database.Error err : sr.getErrors()) {
                    System.debug('Error returned: ' +
                                err.getStatusCode() +
                                ' - ' +
                                err.getMessage());
                }
            }
        }
        
    }

    private static void updateMetricObject(Map<Id,SObject> oldOpps, Map<Id,SObject> newOpps) {
        System.debug(newOpps.keyset());
        System.debug(oldOpps.keyset());
        List<Script_Metric__c> metrics = [SELECT Opportunity__c, Opportunity_Won__c FROM Script_Metric__c WHERE Opportunity__c IN :newOpps.keyset()];
        System.debug(metrics);
        for(Script_Metric__c metric: metrics) {
            Opportunity opp = (Opportunity)newOpps.get(metric.Opportunity__c);
            if(opp == null)
                continue;
            if(opp.StageName == 'Closed Won')
                metric.Opportunity_Won__c = true;
                else 
                metric.Opportunity_Won__c = false;
        }
        update metrics;
    }

    private static void updateScriptJunctionObject(Map<Id,SObject> oldOpps, Map<Id,SObject> newOpps) {
        List<Id> oppIds = new List<Id>();
        oppIds.addAll(oldOpps.keySet());
        Date d = Date.today();
        List<Opporunity_Script_Junction__c> junctions = [SELECT Opportunity__c FROM Opporunity_Script_Junction__c WHERE Opportunity__c IN :oppIds];

        
        for(Opporunity_Script_Junction__c j: junctions) {
            System.debug(j.Id);
            System.debug(j.Opportunity__c);
            System.debug(oldOpps.get(j.Opportunity__c).get('StageName'));
            System.debug(newOpps.get(j.Opportunity__c).get('StageName'));
            if(oldOpps.get(j.Opportunity__c).get('StageName') != 'Closed Won' && newOpps.get(j.Opportunity__c).get('StageName') == 'Closed Won') {
                System.debug('updating date won');
                j.Date_Won__c = d;
            }
        }
        update junctions;
    }
}